### ISSUE TITLE
fwupgrade broken.

### ISSUE THREAD

**Issue by petersilva** [petersilva/drobo-utils#2]
fractal% sudo ./drobom fwupgrade
looking for firmware for: armmarvell 1.254.30359 hw version: b'1.00'
This Drobo should be running:  raptor/firmware/armmarvell/v1.4.2.tdz
looking for: /root/.drobo-utils/armmarvell_1.00_v1.4.2.tdz
local copy already present: /root/.drobo-utils/armmarvell_1.00_v1.4.2.tdz
Reading Firmware from = /root/.drobo-utils/armmarvell_1.00_v1.4.2.tdz
validateFirmware start...
Traceback (most recent call last):
  File "./drobom", line 427, in <module>
    if d.updateFirmwareRepository():
  File "/home/peter/src/drobo-utils/Drobo.py", line 1004, in updateFirmwareRepository
    good = self.PickFirmware(localfw)
  File "/home/peter/src/drobo-utils/Drobo.py", line 749, in PickFirmware
    good = self.validateFirmware()
  File "/home/peter/src/drobo-utils/Drobo.py", line 915, in validateFirmware
    self.fwhdr = struct.unpack('>ll4sl16slllll256sl', self.fwdata[0:312])
AttributeError: 'Drobo' object has no attribute 'fwdata'
fractal%

**Comment by petersilva** [comment]
since the port to python3 (#1 ) fwupgrade is completely busted.
