### ISSUE TITLE
diagnostics dump is busted.

### ISSUE THREAD

**Issue by petersilva** [petersilva/drobo-utils#3]
fractal% sudo ./drobom diag
Dumping Diagnostics...
Traceback (most recent call last):
  File "./drobom", line 381, in <module>
    f = d.dumpDiagnostics()
  File "/home/peter/src/drobo-utils/Drobo.py", line 694, in dumpDiagnostics
    df.write(d)
TypeError: write() argument must be str, not bytes
fractal%

**Comment by petersilva** [comment]
since the port to python3 (#1), diagnostics collection is busted.
