### ISSUE TITLE
Error attempting to see status of Drobo S

### ISSUE THREAD

**Issue by oblongau** [petersilva/drobo-utils#5]
First, thanks to Peter Silva for pointing me to github after I found the old drobo-utils on Sourceforge.

So, using: Drobo S, connected by USB cable. Linux Mint 20.1 (based on Ubuntu 20.04). The Drobo mounts fine and files can be transferred to it. But running "sudo ./drobom view" or "sudo ./drobom status" is as follows;

$ sudo ./drobom view
Traceback (most recent call last):
  File "./drobom", line 344, in <module>
    l = Drobo.DiscoverLUNs(debug, vendor_string)
  File "/home/janette/Downloads/drobo-utils/Drobo.py", line 1462, in DiscoverLUNs
    d = Drobo(potential, DEBUG)
  File "/home/janette/Downloads/drobo-utils/Drobo.py", line 304, in __init__
    cfg = self.GetSubPageConfig()
  File "/home/janette/Downloads/drobo-utils/Drobo.py", line 1097, in GetSubPageConfig
    result = self.__getsubpage(0x01, 'BBBQ')
  File "/home/janette/Downloads/drobo-utils/Drobo.py", line 462, in __getsubpage
    cmdout = self.fd.get_sub_page(paklen, modepageblock, 0, DEBUG)
  File "/home/janette/Downloads/drobo-utils/DroboIOctl.py", line 201, in get_sub_page
    raise IOError("io_hdr status is: %x" % io_hdr.status)
OSError: io_hdr status is: 2

Running "sudo ./drobom -v 128 $* view" as a test brings up the demonstration GUI.

Any ideas?

Thanks.

**Comment by chopnico** [comment]
I'm also having the same problem.

utils version: the latest from source (as of 2021-09-10)
OS: Ubuntu 16.04 (could be the problem, but I don't see any documentation that states 16.04 isn't supported)

Traceback (most recent call last):
  File "./drobom", line 344, in <module>
    l = Drobo.DiscoverLUNs(debug, vendor_string)
  File "/home/wkey/build/drobo-utils/Drobo.py", line 1462, in DiscoverLUNs
    d = Drobo(potential, DEBUG)
  File "/home/wkey/build/drobo-utils/Drobo.py", line 304, in __init__
    cfg = self.GetSubPageConfig()
  File "/home/wkey/build/drobo-utils/Drobo.py", line 1097, in GetSubPageConfig
    result = self.__getsubpage(0x01, 'BBBQ')
  File "/home/wkey/build/drobo-utils/Drobo.py", line 462, in __getsubpage
    cmdout = self.fd.get_sub_page(paklen, modepageblock, 0, DEBUG)
  File "/home/wkey/build/drobo-utils/DroboIOctl.py", line 201, in get_sub_page
    raise IOError("io_hdr status is: %x" % io_hdr.status)
OSError: io_hdr status is: 2

**Comment by stefanfoulis** [comment]
I have the same error. Using commit `820674ff4cea84b18fd86b4a8de49037476caba4` on the `main` branch.

Ubuntu 20.04
DroboPro connected over Firewire.

```
# ./drobom status
Traceback (most recent call last):
  File "./drobom", line 344, in <module>
    l = Drobo.DiscoverLUNs(debug, vendor_string)
  File "/root/tools/drobo-utils/Drobo.py", line 1462, in DiscoverLUNs
    d = Drobo(potential, DEBUG)
  File "/root/tools/drobo-utils/Drobo.py", line 304, in __init__
    cfg = self.GetSubPageConfig()
  File "/root/tools/drobo-utils/Drobo.py", line 1097, in GetSubPageConfig
    result = self.__getsubpage(0x01, 'BBBQ')
  File "/root/tools/drobo-utils/Drobo.py", line 462, in __getsubpage
    cmdout = self.fd.get_sub_page(paklen, modepageblock, 0, DEBUG)
  File "/root/tools/drobo-utils/DroboIOctl.py", line 201, in get_sub_page
    raise IOError("io_hdr status is: %x" % io_hdr.status)
OSError: io_hdr status is: 2
```

**Comment by petersilva** [comment]
2 ... SAM_STAT_CHECK_CONDITION... it´s the drobo or the SCSI stack being unhappy with the request it received.
trying to issue a getSubPageConfig ... a status query page... in older drobo´s the format of that query 3 bytes and then an eight byte (unsigned long long) so a total of 11 bytes.

when we send it that status record it says "CHECK_CONDITION" ... uh... ok... so there is something wrong... I guess the obvious ask is:   ./drobom -v 127 status

**Comment by petersilva** [comment]
been too long... I mean -v 255 instead of --debug...

**Comment by stefanfoulis** [comment]
@petersilva thanks for the quick response 🙇‍♂️ 

`./drobom -v 127 status`:

```
# ./drobom -v 127 status
examining:  /dev/sda
id:  (0, 0, 0, 0, 'ATA     ')
found a Drobo
appending new lundevs to devices: []
examining:  /dev/sdb
rejected: failed to construct LUN pdio
examining:  /dev/sdc
id:  (5, 0, 0, 2, 'DROBO   ')
found a Drobo
appending new lundevs to devices: [['/dev/sda']]
examining:  /dev/sdd
id:  (5, 0, 0, 1, 'DROBO   ')
found a Drobo
appending to lundevs...
examining:  /dev/sde
id:  (5, 0, 0, 0, 'DROBO   ')
found a Drobo
appending to lundevs...
returning list:  [['/dev/sda'], ['/dev/sdc', '/dev/sdd', '/dev/sde']]
trying:  ['/dev/sda']
__init__
getsubpage
DMIP sub_page query:0x01 pattern: >BBHBBBQ
mcb 000:
5a 00 3a 01 00 00 00 00 0f 00
4 before ioctl, sense_buffer_len= 0
5 after ioctl, result=0 status: 2 driver_status: 8 host_status: 0 sb_len_wr: 0 resid: 0
Traceback (most recent call last):
  File "./drobom", line 344, in <module>
    l = Drobo.DiscoverLUNs(debug, vendor_string)
  File "/root/tools/drobo-utils/Drobo.py", line 1462, in DiscoverLUNs
    d = Drobo(potential, DEBUG)
  File "/root/tools/drobo-utils/Drobo.py", line 304, in __init__
    cfg = self.GetSubPageConfig()
  File "/root/tools/drobo-utils/Drobo.py", line 1097, in GetSubPageConfig
    result = self.__getsubpage(0x01, 'BBBQ')
  File "/root/tools/drobo-utils/Drobo.py", line 462, in __getsubpage
    cmdout = self.fd.get_sub_page(paklen, modepageblock, 0, DEBUG)
  File "/root/tools/drobo-utils/DroboIOctl.py", line 201, in get_sub_page
    raise IOError("io_hdr status is: %x" % io_hdr.status)
OSError: io_hdr status is: 2
__del__
```

**Comment by stefanfoulis** [comment]
@petersilva is there something I can do to help debug this issue?

I tried again with `27cc8884f6d63f843ce3d140e2e240ce2f331b63` and still get the same error.
I can help with python stuff, but am totally out of my depth with the lower level SCSI stuff.

**Comment by stefanfoulis** [comment]
`result = self.__getsubpage(0x01, 'BBBQ')`
🤤  mmmmhhhhh. BBQ.


I'll try this with USB instead of firewire on the DroboPro and also with an old 4 bay drobo I have somewhere in the workshop. I wonder if the results will be any different.
Unfortunately I don't have any modern Drobos around to test with.

**Comment by petersilva** [comment]
is /dev/sda really a Drobo? it says "Drobo   ' in the vendor field for /dev/sdc, /dev/sdd, and /dev/sde... but it says 'ATA    ' for /dev/sda... so maybe /dev/sda is just a completely different disk, and we just need to ignore the result (put a try/except around it, and in the except, conclude it is not a Drobo...)

**Comment by petersilva** [comment]
I think you can coax it by forcing the vendor string (note the trainling spaces!) , try:
```

drobom -s 'DROBO   '  -v 128 status

```

**Comment by petersilva** [comment]
looking in the code... there was an if statement replacing a try/except for debugging purposes. I put it back, and it should work now, even without -s.

**Comment by petersilva** [comment]
oh, I guess I should say: "git pull" and it should be better.

**Comment by stefanfoulis** [comment]
🥳 🎈  Thank you very much. With that change it works for me now 👍 .

**Comment by oblongau** [comment]
And thanks from me, too. This now works and brings up the GUI. However, the computer this is running on has a high resolution screen (3840 x 2160) so the GUI is quite small and the text too small to be easily readable. The window can be resized but the text size does not change.
How would that be fixed? Any pointers as to where to look would be appreciated. (Should this question be given its own issue?)
Thanks.

**Comment by petersilva** [comment]
I googled a bit. drobom is built using QT5.  found this: https://wiki.archlinux.org/title/HiDPI#Qt_5
based on that, I did this:
```

fractal% export QT_AUTO_SCREEN_SCALE_FACTOR=0
fractal% export QT_SCALE_FACTOR=2
fractal% ./drobom -v 128 view

```
and got a huge GUI.   yeah... this should probably be a separate issue.

**Comment by petersilva** [comment]
This also works, without polluting the environment for all other QT apps you start:
`
fractal% QT_SCALE_FACTOR=2 ./drobom -v 128 view
`

**Comment by petersilva** [comment]
Issue #6 opened.
